"""empty message

Revision ID: 636a9031d3e5
Revises: 80dd48944b4b
Create Date: 2021-03-17 11:55:17.330974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636a9031d3e5'
down_revision = '80dd48944b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'past_shows_count')
    # ### end Alembic commands ###
